baseURL = 'https://www.hugovmonteiro.net/'
languageCode = 'en-us'
title = 'hugo V monteiro'

# Google analytics code
#googleAnalytics = "G-xxxxxxxxx"

[module]
[[module.imports]]
path = "github.com/tomfran/typo"

[taxonomies]
tag = 'tags'

[params]
faviconPath = '/images'
# Meta description
description = 'Thoughts on technology, the world, and life.'

# Appearance settings
theme = 'light'                    # 'auto | light | dark'
colorPalette = 'default'           # https://tomfran.github.io/typo-wiki/features/appearance/
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
{{< figure src="/images/home.jpg" class="figure" >}}  
You reached the personal website of _Hugo Monteiro_, a **technologist** at heart and a senior **IT Solution Designer** and **Systems Architect** with over _25 years of experience_ delivering impactful _IT and R&D solutions_ across some of the world’s largest technology corporations.  
  
Outside the corporate environment, _Hugo_ has been actively involved in the [open-source](https://opensource.org/) movement, developing his own applications and tools whenever a specific need arises.
  
  
Beyond technology, Hugo is deeply **curious** about life and society as a whole. He has a **strong drive** to understand how and why things work, always trying to go beyond the surface and explore subjects from the inside out.  
  
_Hugo is also a **musician**, **DIY** enthusiast, **mechanics** aficionado and an avid **writer**._  
   
You can check more **details about himself** in the [about](about) page.
  
If you're interested in his **professional career** you can jump to his _LinkedIn_ page [here](https://www.linkedin.com/in/hvmonteiro/).
  
The **_Musician side_** is found at it's dedicated website [here](https://www.hugovmonteiro.com).

You should also check his recent **writings** in his blog **_Intriguing Mind_** on SubStack [here](https://intriguingmind.substack.com/), or on the local section [writings](/writings) at this site.
"""

# Collection to display on home
#homeCollectionTitle = 'writings'
#homeCollection = 'home'

# Content Directory
contentDir = "content"

# Lists parameters
paginationSize = 15
paginationTagsSize = 50
listSummaries = true # List summary OR first block of content of all articles
listDateFormat = '2 Jan 2006'
showListDate = false

#showFooter = true
footerContent = "_Copyright_ © 2026 _Hugo Monteiro_"

# Mermaid Diagrams
#mermaidTheme = "neutral"
[markup.goldmark.renderer]
unsafe = true


# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = false # Set to false to hide the last crumb, i.e, the current page.
home = "~"

# Social icons
[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/hvmonteiro/"

[[params.social]]
name = "SubStack"
url = "https://intriguingmind.substack.com/"

[[params.social]]
name = "GitHub"
url = "https://github.com/hvmonteiro"

#[[params.social]]
#name = "Mastodon"
#url = "https://mastodon.online/@hvmonteiro"

#[[params.social]]
#name = "Threads"
#icon = "fab fa-threads"
#url = "https://www.threads.com/@hugo.v.monteiro"

#[[params.social]]
#name = "Buy me a Coffee"
#url = "https://buymeacoffee.com/hvmonteiro"
#icon = "fab fa-buymeacoffee"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "writings"
url = "/writings"

[[params.menu]]
name = "tech corner"
url = "/tech-corner"

[[params.menu]]
name = "tags"
url = "/tags"

[[params.menu]]
name = "intriguing mind&#x2197"
url = "https://intriguingmind.substack.com/"
rel = "external"

[[params.menu]]
name = "about"
url = "/about"


[markup]


[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

# Syntax highlight on code blocks
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

# https://umami.is/
[params.umami] 
enable = true
websiteId = "unique-website-id"
jsLocation = "http://example.org/umami.js"

